apiVersion: v1
kind: Service
metadata:
  name: transaction-app-svc
spec:
  selector:
    app: transaction-app
  ports:
    - protocol: "TCP"
      port: 5050
      targetPort: 5050
  type: LoadBalancer
